In [320]:
import numpy as np
import pandas as pd
import re

In [321]:
data = 'https://www.ndbc.noaa.gov/data/realtime2/46029.spec'
article_read = pd.read_csv(data, sep='\s+', delimiter=' ', encoding="utf-8", skipinitialspace=True)

In [322]:
article_read.head()

,#YY,MM,DD,hh,mm,WVHT,SwH,SwP,WWH,WWP,SwD,WWD,STEEPNESS,APD,MWD
0,#yr,mo,dy,hr,mn,m,m,sec,m,sec,-,degT,-,sec,degT
1,2019,03,21,08,00,2.0,1.9,13.8,0.5,4.0,W,S,SWELL,8.4,264
2,2019,03,21,07,00,2.0,1.9,13.8,0.5,4.3,WSW,S,SWELL,8.2,249
3,2019,03,21,06,00,2.0,1.9,12.9,0.5,3.3,W,SSW,SWELL,7.9,263
4,2019,03,21,05,00,2.1,2.0,12.9,0.6,3.4,W,S,SWELL,7.5,271

In [334]:
short_table = article_read.drop(article_read.iloc[:,3:6,], axis=1)

In [351]:
short_table.where(short_table > 2019).head()

    #YY  MM  DD  SwH   SwP  WWH  WWP  SwD   WWD STEEPNESS  APD   MWD   Date
0   #yr  mo  dy    m   sec    m  sec    -  degT         -  sec  degT  value
1  2019  03  21  1.9  13.8  0.5  4.0    W     S     SWELL  8.4   264  value
2  2019  03  21  1.9  13.8  0.5  4.3  WSW     S     SWELL  8.2   249  value
3  2019  03  21  1.9  12.9  0.5  3.3    W   SSW     SWELL  7.9   263  value
4  2019  03  21  2.0  12.9  0.6  3.4    W     S     SWELL  7.5   271  value